### ISSUE TITLE
HOTP ERR: Too long or badly formatted base32 string. It should be not longer than 32 characters.

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/nitrokey-hotp-verification#6]
In Heads when sealing HOTP:
```
HOTP code verification application via Librem Key, version 1.1
ERR: Too long or badly formatted base32 string. It should be not longer than 32 characters.
Error occurred, status code 24: Invalid base32 string
ERROR: Setting HOTP secret on Librem Key failed!
Error settings HOTP secret, re-enter Admin PIN and try again:
```

**Comment by tlaurion** [comment]
@kylerankin ?

Sometimes it works after the forth loop [I wrapped over that code](https://gitlab.com/tlaurion/heads/blob/oem_reownership-staging/initrd/bin/gui-init#L126) else it fails too often leaving TOTP sealed while HOTP isn't.

**Comment by szszszsz** [comment]
Relevant lines for error string reference:
https://github.com/Nitrokey/nitrokey-hotp-verification/blob/7807d972b5fbbc919120256e991b05343727608a/operations.c#L52-L63

**Comment by szszszsz** [comment]
@tlaurion Could you paste please the failing `SECRET_B32` inputs for reference?

**Comment by marmarek** [comment]
The TOTP secret (I got as QR code): `JVOKTGWL6TWLRQBKUEEUYVGRJZQBM2EH`
From what I see in scripts, the same value is provided to `libremkey_hotp_initialize`, so it should be it.
This value base32 decoded contains NUL byte, so it may be problematic when passing it over env variable or command argument. Maybe the script should require already base32 encoded value?

**Comment by szszszsz** [comment]
@marmarek This is my guess as well. Proposed secret transport via the base32 (before `libremkey_hotp_initialize` would get it) should solve the issue.

**Comment by tlaurion** [comment]
@szszszsz Problem is still present. It seems that regeneration of secret is not done prior to try to seal it.
Will investigate, but it doesn't still fully fix the problem.

**Comment by szszszsz** [comment]
@tlaurion I have not fixed it, but merely added a test confirming that this is not a fault of the client application. This has to be corrected on the caller side.
As @marmarek has noticed, the problem is the null byte being transferred around in raw string, while it should be in an encoded version. Null in a raw string effectively cuts the secret, and the `0` is ignored as well.

**Comment by szszszsz** [comment]
Setting `invalid` label, as the problem lies out of scope of this project. 
Closing. Please reopen, if you think otherwise.
